<h1>Data Toolkit</h1>

1. Demonstrate three different methods for creating identical 2D arrays in NumPy. Provide the code for each method and the final output after each method.

In [3]:
#Method1
import numpy as np

# Create a 2D array using numpy.array()
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Method 1: Using numpy.array()")
print(arr)

Method 1: Using numpy.array()
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#Method2
import numpy as np

# Create a 2D array using numpy.zeros()
arr = np.zeros((3, 3))

print("Method 2: Using numpy.zeros()")
print(arr)

Method 2: Using numpy.zeros()
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
#Method3
import numpy as np

# Create a 2D array using numpy.ones()
arr = np.ones((3, 3))

print("Method 3: Using numpy.ones()")
print(arr)

Method 3: Using numpy.ones()
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


2. Using the Numpy function, generate an array of 100 evenly spaced numbers between 1 and 10 and Reshape that 1D array into a 2D array

In [6]:
import numpy as np

# Generate an array of 100 evenly spaced numbers between 1 and 10
arr = np.linspace(1, 10, 100)

# Reshape the 1D array into a 2D array with 10 rows and 10 columns
arr_2d = arr.reshape((10, 10))

print(arr_2d)

[[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
   1.54545455  1.63636364  1.72727273  1.81818182]
 [ 1.90909091  2.          2.09090909  2.18181818  2.27272727  2.36363636
   2.45454545  2.54545455  2.63636364  2.72727273]
 [ 2.81818182  2.90909091  3.          3.09090909  3.18181818  3.27272727
   3.36363636  3.45454545  3.54545455  3.63636364]
 [ 3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
   4.27272727  4.36363636  4.45454545  4.54545455]
 [ 4.63636364  4.72727273  4.81818182  4.90909091  5.          5.09090909
   5.18181818  5.27272727  5.36363636  5.45454545]
 [ 5.54545455  5.63636364  5.72727273  5.81818182  5.90909091  6.
   6.09090909  6.18181818  6.27272727  6.36363636]
 [ 6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
   7.          7.09090909  7.18181818  7.27272727]
 [ 7.36363636  7.45454545  7.54545455  7.63636364  7.72727273  7.81818182
   7.90909091  8.          8.09090909  8.18181818]
 [ 8.272

3. Explain the following terms:
<ul><li>The difference in np.array, np.asarray and np.asanyarray.</li>
<li>The difference between Deep copy and shallow copy.</li></ul>

The difference between np.array, np.asarray, and np.asanyarray in NumPy is primarily related to how they handle the input data and whether they make a copy of the data or not.

np.array: This function creates a new array from the input data. It makes a copy of the input data by default. This means that if you modify the original data, the changes will not be reflected in the new array.

np.asarray: This function also creates a new array from the input data. However, it does not make a copy of the input data by default. Instead, it tries to use the input data as is. If the input data is already an array, it will not make a copy. This can be useful if you want to avoid making a copy of the data and you are sure that the input data is an array.

np.asanyarray: This function is similar to np.asarray, but it also checks if the input data is a subclass of ndarray. If it is, it will return the input data as is, without making a copy. This can be useful if you want to preserve the original data and its subclass relationships.


The difference between deep copy and shallow copy is primarily related to how they handle nested objects.

Shallow Copy: A shallow copy creates a new object that references the same inner objects as the original. This means that if you modify the inner objects, the changes will be reflected in both the original and the copy. However, if you modify the top-level object, the changes will only be reflected in the original.

Deep Copy: A deep copy creates a completely independent copy of both the object and its nested objects. This means that if you modify the nested objects, the changes will only be reflected in the copy, and not in the original. This can be useful if you want to preserve the original data and its nested objects, and you want to make changes to the nested objects without affecting the original.

Here's a simple example that demonstrates the difference between shallow copy and deep copy:

python
<pre>
import copy

# Original list
original_list = [[1, 2, 3], [4, 5, 6]]

# Shallow copy
shallow_copy = copy.copy(original_list)

# Deep copy
deep_copy = copy.deepcopy(original_list)

# Modify the first element of the shallow copy
shallow_copy[0][0] = 10

# Modify the first element of the deep copy
deep_copy[0][0] = 20

print("Original List:", original_list)
print("Shallow Copy:", shallow_copy)
print("Deep Copy:", deep_copy)
</pre>

Output:
<pre>
Original List: [[1, 2, 3], [4, 5, 6]]
Shallow Copy: [[10, 2, 3], [4, 5, 6]]
Deep Copy: [[20, 2, 3], [4, 5, 6]]
</pre>

In this example, we can see that modifying the shallow copy affects the original list, but modifying the deep copy does not affect the original list.

4. Generate a 3x3 array with random floating-point numbers between 5 and 20. Then, round each number in the array to 2 decimal places.

In [ ]:
import numpy as np

# Set the seed for reproducibility (optional)
np.random.seed(42)

# Generate the 3x3 array with random floating-point numbers between 5 and 20
arr = np.random.uniform(5, 20, size=(3, 3))

# Round each number in the array to 2 decimal places
arr_rounded = np.round(arr, decimals=2)

# Print the rounded array
print(arr_rounded)


[[10.62 19.26 15.98]
 [13.98  7.34  7.34]
 [ 5.87 17.99 14.02]]


This code snippet uses the np.random.uniform function from the NumPy library to generate random numbers between 5 and 20. The size parameter is set to (3, 3) to create a 3x3 array. The np.round function is then used to round each number in the array to 2 decimal places

5.Create a NumPy array with random integers between 1 and 10 of shape (5, 6). After creating the array perform the following operations
a)extract all even integers from array
b)extract all odd integers from array

In [ ]:
import numpy as np

# Set the seed for reproducibility (optional)
np.random.seed(42)

# Create the array of random integers between 1 and 10
arr = np.random.randint(1, 11, size=(5, 6))

# Extract all even integers from the array
even_nums = arr[arr % 2 == 0]

# Extract all odd integers from the array
odd_nums = arr[arr % 2 != 0]

# Print the array and the extracted even and odd integers
print("Array:")
print(arr)
print("\nEven Integers:")
print(even_nums)
print("\nOdd Integers:")
print(odd_nums)


Array:
[[ 7  4  8  5  7 10]
 [ 3  7  8  5  4  8]
 [ 8  3  6  5  2  8]
 [ 6  2  5  1 10  6]
 [ 9  1 10  3  7  4]]

Even Integers:
[ 4  8 10  8  4  8  8  6  2  8  6  2 10  6 10  4]

Odd Integers:
[7 5 7 3 7 5 3 5 5 1 9 1 3 7]


In this code, we use np.random.randint function from the NumPy library to create a 5x6 array of random integers between 1 and 10. We then use boolean indexing to extract the even integers using the condition arr % 2 == 0 and the odd integers using the condition arr % 2 != 0.

6.Create a 3D NumPy array of shape (3, 3, 3) containing random integers between 1 and 10. Perform the following operations
a)find the indices of the maximum values along each depth level(third axis)
b)perform element wise multiplication of between both array

In [1]:
import numpy as np

# Set the seed for reproducibility (optional)
np.random.seed(42)

# Create the 3D array of random integers between 1 and 10
arr = np.random.randint(1, 11, size=(3, 3, 3))

# Find the indices of the maximum values along each depth level (third axis)
max_indices = np.argmax(arr, axis=2)

# Perform element-wise multiplication between the array and its transpose
elementwise_mult = arr * arr.T

# Print the array, the indices of the maximum values, and the element-wise multiplication
print("Array:")
print(arr)
print("\nIndices of Maximum Values along Third Axis:")
print(max_indices)
print("\nElement-wise Multiplication:")
print(elementwise_mult)


Array:
[[[ 7  4  8]
  [ 5  7 10]
  [ 3  7  8]]

 [[ 5  4  8]
  [ 8  3  6]
  [ 5  2  8]]

 [[ 6  2  5]
  [ 1 10  6]
  [ 9  1 10]]]

Indices of Maximum Values along Third Axis:
[[2 2 2]
 [2 0 2]
 [0 1 2]]

Element-wise Multiplication:
[[[ 49  20  48]
  [ 25  56  10]
  [  9  35  72]]

 [[ 20  16  16]
  [ 56   9  60]
  [ 35   4   8]]

 [[ 48  16  25]
  [ 10  60  36]
  [ 72   8 100]]]


In this code, we use np.random.randint function from the NumPy library to create a 3D array of random integers between 1 and 10 with a shape of (3, 3, 3). We then use np.argmax function with axis=2 to find the indices of the maximum values along each depth level (third axis). Finally, we perform element-wise multiplication between the array and its transpose using the * operator.

7.Clean and transform the 'Phone' column in the sample dataset to remove non-numeric characters and  convert it to a numeric data type.also display the table attributes and data types of each column

In [ ]:
import pandas as pd

# Read the People_Dataset into a DataFrame
df = pd.read_csv('People_Dataset.csv')

# Filter the DataFrame based on the conditions
filtered_df = df[(df['Last Name'].str.contains('Duke')) & (df['Gender'] == 'female') & (df['Salary'] < 85000)]

# Display the first 10 rows of the filtered DataFrame
print(filtered_df.head(10))

# Extract the 'Salary' column as a series and display its last 5 values
salary_series = filtered_df['Salary']
print(salary_series.tail(5))


In [ ]:
10.Create a 7*5 Dataframe in Pandas using a series generated from 35 random integers between 1 to 6?

In [3]:
import pandas as pd
import numpy as np

# Set the seed for reproducibility (optional)
np.random.seed(42)

# Create the first series with random numbers ranging from 10 to 50
series1 = pd.Series(np.random.randint(10, 51, size=50))

# Create the second series with random numbers ranging from 100 to 1000
series2 = pd.Series(np.random.randint(100, 1001, size=50))

# Create a DataFrame by joining the two series by column
df = pd.DataFrame({'col1': series1, 'col2': series2})

# Print the DataFrame with the changed column names
print(df)


    col1  col2
0     48   661
1     38   971
2     24   487
3     17   101
4     30   489
5     48   665
6     28   205
7     32   871
8     20   921
9     20   576
10    33   802
11    45   501
12    49   829
13    33   655
14    12   261
15    31   301
16    11   369
17    33   962
18    39   915
19    47   370
20    11   555
21    30   561
22    42   826
23    21   351
24    31   801
25    34   395
26    36   824
27    37   819
28    25   848
29    24   437
30    12   978
31    46   152
32    16   891
33    30   316
34    18   863
35    48   287
36    27   479
37    13   592
38    34   140
39    23   256
40    18   114
41    35   912
42    11   164
43    29   956
44    37   938
45    16   620
46    17   443
47    44   228
48    23   747
49    26   571


In [ ]:
import pandas as pd

# Read the People_Dataset into a DataFrame
df = pd.read_csv('People_Dataset.csv')

# Delete the 'Email', 'Phone', and 'DateofBirth' columns
df = df.drop(['Email', 'Phone', 'DateofBirth'], axis=1)

# Delete the rows containing any missing values
df = df.dropna()

# Print the final output
print(df)


In [ ]:
13.

13. Create two NumPy arrays, x and y, each containing 100 random float values between 0 and 1. Perform the following tasks using Matplotlib and NumPy: 
a) Create a scatter plot using x and y, setting the color of the points to red and the marker style to 'o'. 
b) Add a horizontal line at y = 0.5 using a dashed line style and label it as 'y = 0.5'. 
c) Add a vertical line at x = 0.5 using a dotted line style and label it as 'x = 0.5'. 
d) Label the x-axis as 'X-axis' and the y-axis as 'Y-axis'. 
e) Set the title of the plot as 'Advanced Scatter Plot of Random Values'. 
f) Display a legend for the scatter plot, the horizontal line, and the vertical line. 


14. Create a time-series dataset in a Pandas DataFrame with columns: 'Date', 'Temperature', 'Humidity' and Perform the following tasks using Matplotlib: 
a) Plot the 'Temperature' and 'Humidity' on the same plot with different y-axes (left y-axis for 'Temperature' and right y-axis for 'Humidity'). 
b) Label the x-axis as 'Date'. 
c) Set the title of the plot as 'Temperature and Humidity Over Time'. 


15. Create a NumPy array data containing 1000 samples from a normal distribution. Perform the following tasks using Matplotlib: a) Plot a histogram of the data with 30 bins. 
b) Overlay a line plot representing the normal distribution's probability density function (PDF). 
c) Label the x-axis as 'Value' and the y-axis as 'Frequency/Probability'. 
d) Set the title of the plot as 'Histogram with PDF Overlay'. 


16. Set the title of the plot as 'Histogram with PDF Overlay'. 


17. Create a Seaborn scatter plot of two random arrays, color points based on their position relative to the origin (quadrants), add a legend, label the axes, and set the title as 'Quadrant-wise Scatter Plot'.


18. With Bokeh, plot a line chart of a sine wave function, add grid lines, label the axes, and set the title as 'Sine Wave Function'. 


19. Using Bokeh, generate a bar chart of randomly generated categorical data, color bars based on their values, add hover tooltips to display exact values, label the axes, and set the title as 'Random Categorical Bar Chart'. 


20. Using Plotly, create a basic line plot of a randomly generated dataset, label the axes, and set the title as 'Simple Line Plot'. 

21. Using Plotly, create an interactive pie chart of randomly generated data, add labels and percentages, set the title as 'Interactive Pie Chart'.